services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/var/www
      - /var/www/node_modules
    networks:
      - project-api

networks:
  project-api:
    driver: bridge